### ISSUE TITLE
Breakpoint 1: no locations (pending).

### ISSUE THREAD

**Issue by ghost** [bartcone/reverse-engineering-blog#1]
Can you help me? what's wrong ?
```
Tests-MacBook-Pro:~ test123$ lldb
(lldb) b -[UIPopoverPresentationController dimmingViewWasTapped:]
Breakpoint 1: no locations (pending).
Breakpoint set in dummy target, will get copied into future targets.
(lldb) b -[UIPopoverPresentationController dimmingViewWasTapped:]
Breakpoint 2: no locations (pending).
Breakpoint set in dummy target, will get copied into future targets.
(lldb) b -[UIPopoverPresentationController dimmingViewWasTapped:]
Breakpoint 3: no locations (pending).
Breakpoint set in dummy target, will get copied into future targets.
(lldb) 
```

**Comment by bartcone** [comment]
@henrymark92 that output looks like you started `lldb` straight from terminal? Did you download the Xcode project I referenced in the post?

**Comment by ghost** [comment]
hi @bartcone 
1. I started lldb from terminal. How to start lldb from hopper?
2. I didn't use xcode project your referenced in the post. I'm using xcode 9.0
3. How to convert  source code decompiled via hopper to source code clean( source code can be understand)?
4. how to  make pseudo code translated into Objective-C?
Please you help me. !!!
Thanks
